## devops@withdrawals-teku-besu-1
data-path="/tmp/besu"
genesis-file="besu.json"
static-nodes-file="static-nodes.json"
network-id=1337806
max-peers=100
rpc-http-enabled=true
rpc-http-api=["ADMIN","CLIQUE","MINER","ETH","NET","DEBUG","TXPOOL","ENGINE","TRACE"]
rpc-http-host="0.0.0.0"
rpc-http-port=8545
engine-rpc-enabled=true
engine-rpc-port=8551
engine-host-allowlist=["*"]
rpc-http-cors-origins=["*"]
rpc-ws-enabled=true
rpc-ws-api=["ADMIN","CLIQUE","MINER","ETH","NET","DEBUG","TXPOOL","ENGINE","TRACE"]
rpc-ws-host="0.0.0.0"
host-allowlist=["*"]
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=8002
p2p-enabled=true
#p2p-host=142.93.108.142
#p2p-host="125.63.11.148"
sync-mode="FULL"
data-storage-format="BONSAI"
engine-jwt-enabled=true
engine-jwt-secret="jwtsecret.txt"
miner-coinbase="0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134" 
#bootnodes=["enode://b896e651b9d100ece367bf6a360b22b7e3032f542c1bffcc102f94e79a44d74b227bbcf67218e25d375ddd50beaf229135d3e42a260717c3d82eb897ce8b9069@167.71.60.16:30303"]


#--p2p-host=161.35.83.94 
